import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Sparkles, Cpu, Layers, CheckCircle2 } from 'lucide-react';

export const Home: React.FC = () => {
  return (
    <div className="relative overflow-hidden py-12 sm:py-20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* Hero Section */}
        <div className="text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-indigo-500/30 bg-indigo-500/10 px-4 py-1.5 text-xs font-semibold text-indigo-400">
            <Sparkles className="h-3.5 w-3.5" />
            AI-Powered Multi-Agent Curriculum Intelligence
          </div>

          <h1 className="mt-6 font-display text-4xl font-extrabold tracking-tight text-white sm:text-6xl lg:text-7xl">
            Structured Learning Roadmaps for{' '}
            <span className="bg-gradient-to-r from-indigo-400 via-purple-400 to-emerald-400 bg-clip-text text-transparent">
              294+ Domains
            </span>
          </h1>

          <p className="mx-auto mt-6 max-w-2xl text-base text-slate-400 sm:text-lg">
            From Frontend & AI Engineering to Mechanical, Civil Engineering, Finance & Design. Generated by a 16-agent AI architecture with directed dependency graphs, exact 5 real projects, verified resources, and job-readiness benchmarks.
          </p>

          <div className="mt-8 flex items-center justify-center gap-4">
            <Link
              to="/roadmaps"
              className="flex items-center gap-2 rounded-xl bg-indigo-600 px-6 py-3 text-sm font-bold text-white shadow-xl shadow-indigo-600/30 transition hover:bg-indigo-500"
            >
              Explore Roadmaps
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              to="/admin/domains"
              className="rounded-xl border border-slate-700 bg-slate-900 px-6 py-3 text-sm font-bold text-slate-200 transition hover:bg-slate-800 hover:text-white"
            >
              Admin Dashboard
            </Link>
          </div>
        </div>

        {/* Feature Highlights */}
        <div className="mt-20 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 backdrop-blur-md">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-500/20 text-indigo-400">
              <Cpu className="h-5 w-5" />
            </div>
            <h3 className="mt-4 text-base font-bold text-white">16 AI Agents</h3>
            <p className="mt-1 text-xs text-slate-400">
              Multi-agent workflow with Critic and Targeted Repair loops ensuring &ge;90 quality scores.
            </p>
          </div>

          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 backdrop-blur-md">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-purple-500/20 text-purple-400">
              <Layers className="h-5 w-5" />
            </div>
            <h3 className="mt-4 text-base font-bold text-white">Directed Graphs</h3>
            <p className="mt-1 text-xs text-slate-400">
              Cycle-free directed acyclic graph (DAG) rendered with React Flow & path branch switching.
            </p>
          </div>

          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 backdrop-blur-md">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/20 text-emerald-400">
              <CheckCircle2 className="h-5 w-5" />
            </div>
            <h3 className="mt-4 text-base font-bold text-white">5 Real Projects</h3>
            <p className="mt-1 text-xs text-slate-400">
              Exactly 5 domain-tailored projects progressing from Beginner to Capstone standard.
            </p>
          </div>

          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 backdrop-blur-md">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-500/20 text-amber-400">
              <Sparkles className="h-5 w-5" />
            </div>
            <h3 className="mt-4 text-base font-bold text-white">Parallel Engine</h3>
            <p className="mt-1 text-xs text-slate-400">
              Worker pool processes 5 domains concurrently with Gemini API rate-limiter controls.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
